<?php
/**
 * Sistema de Idiomas - Smart Office 4.0 (compatível com PHP 7.2)
 */
class LanguageManager {
  /** @var array */
  private $strings = [];

  public function __construct($lang = 'pt_BR') { $this->loadLanguage($lang); }

  public function loadLanguage($lang) {
    $languages = [
      'pt_BR' => [
        //  login.php
        'faca_login'                              => 'Faça login para iniciar sua sessão.',
        'usuario'                                 => 'Usuário',
        'senha'                                   => 'Senha',
        'lembrar'                                 => 'Lembrar',
        'entrar'                                  => 'Entrar',
        'esqueci_senha'                           => 'Esqueci minha senha',
        // Toasts
        'falha_login'                             => 'Falha no login',
        'usuario_nao_existe'                      => 'Usuário não existe.',
        'senha_invalida'                          => 'Senha inválida.',
        'credenciais_invalidas'                   => 'Credenciais inválidas',
        'login_sucesso'                           => 'Login realizado com sucesso',
        'bem_vindo'                               => 'Bem-vindo ao Smart Office 4.0',
        'acessando_sistema'                       => 'Acessando sistema',
        'validando_credenciais'                   => 'Validando credenciais...',
        'preencha_usuario_senha'                  => 'Preencha usuário e senha.',
        'usuario_senha_incorretos'                => 'Usuário ou senha incorretos.',
        'redirecionando'                          => 'Você será redirecionado automaticamente...',
        'loading'                                 => 'Carregando',

        //  dashboard.php
        'dashboard'                               => 'Painel',

        // forgot-password.php
        'recuperar_senha'                         => 'Recuperar senha',

        // preferences.php
        'preferencias'                            => 'Preferências',
        'config_server'                           => 'Configuração do servidor',
        'config_home'                             => 'Configuração da home',
        'config_exibir_home'                      => 'Exibir página inicial',
        'config_nao_exibir'                       => 'Não exibir página inicial',
        'config_nao_exibir_help'                  => 'Se selecionar esta opção, a página inicial não será exibida.',
        'config_idioma'                           => 'Configuração do idioma',
        'config_idioma_help'                      => 'Selecione o idioma preferido para o sistema.', 
        'config_ptbr'                             => 'Português (Brasil)',
        'config_enus'                             => 'English (United States)',
        'config_eses'                             => 'Español (España)',
        'config_salva'                            => 'Salvar preferências',

        'config_api_ia'                           => 'Configuração da APIKey do GROQ',
        'config_cole_apikey'                      => 'Cole aqui sua chave (sk-...)',
        'config_api_ia_help'                      => 'Insira a chave da API de IA fornecida pela OpenAI.',
        'config_atual_mascarada'                  => 'Chave atual (mascarada):',
        'config_erro'                             => 'Erro',
        'config_sucesso'                          => 'Sucesso',
        'config_info'                             => 'Informação',
        'config_salva_ok'                         => 'Preferências salvas.',
        'config_api_salva_ok'                     => 'APIKey Atualizada com sucesso.',
        'config_api_vazia_ignorada'               => 'Chave vazia — nada a atualizar.',
        'config_csrf_invalido'                    => 'Sessão expirada. Atualize a página e tente novamente.',
        'config_seguranca_dica'                   => 'Dica: não exibimos a chave completa; informe uma nova para atualizar.',
        'config_connection_success'               => 'Conexão OK',
        'config_connection_fail'                  => 'Falha: ',
        'config_db_exist'                         => 'Banco inexistente',

        // tabelas.php
        'list_database'                           => 'Lista de Tabelas',

        // novagrafico.php
        'configurar_metricas_graficos'            => 'Configurar Métricas',
        'configuracoes_metricase_graficos'        => 'Configurar Métricas &amp; Gráficos',
        'modelo_de_exibicao'                      => '3. Modelos de exibição (dso_model_grafico)',
        'definir_join'                            => '2. Definir JOINs',
        'definir_metrica'                         => '1. Definir métrica',
        'nome_da_metrica'                         => 'Nome da métrica *',
        'tabela_principal'                        => 'Tabela principal *',
        'tabela_schema'                           => 'Tabelas do schema',
        'colunas_grupo'                           => 'Colunas de agrupamento (coluna_grupo)',
        'colunas_grupo_help'                      => 'Selecione uma ou mais colunas para agrupar (por status, por filial, etc).',
        'colunas_valor'                           => 'Coluna de valor (coluna_valor)',
        'colunas_valor_help'                      => 'Se não selecionar nada, será usado <code>COUNT(*)</code>.',
        'filtro_where'                            => 'Filtro WHERE (opcional)',
        'cancelar_edicao'                         => 'Cancelar edição',
        'modelo_metrica'                          => 'Métrica',
        'metricas_cadastradas'                    => 'Métricas cadastradas',
        'editando_id'                             => 'Editando ID #',
        'tabela_juntar'                           => 'Tabela a juntar',
        'tabela_juntar_help'                      => 'Ex.: clientes, contratos, academia, etc.',
        'alias'                                   => 'Alias',
        'tipo_join'                               => 'Tipo JOIN',
        'condicao_on'                             => 'Condição ON *',
        'condicao_on_help'                        => 'Use aliases coerentes com a query que você vai gerar (ex.: ct, c, a).',
        'nenhum_join_cadastrado'                  => 'Nenhum JOIN cadastrado ainda.',
        'selecione'                               => '-- selecione --',
        'descricao'                               => 'Descrição',
        'agregacao'                               => 'Agregação',
        'count'                                   => 'CONTAGEM',
        'sum'                                     => 'SOMA',
        'avg'                                     => 'MÉDIA',
        'min'                                     => 'MÍNIMO',
        'max'                                     => 'MÁXIMO', 
        'nenhuma_metrica_cadastrada'              => 'Nenhuma métrica cadastrada ainda.',
        'nome'                                    => 'Nome',
        'acoes'                                   => 'Ações',
        'tabela_alias'                            => 'Tabela (alias)',
        'condicao_onn'                            => 'ON',
        'box_azul'                                => 'Azul',
        'box_amarelo'                             => 'Amarelo',
        'box_verde'                               => 'Verde',
        'box_vermelho'                            => 'Vermelho',
        'kpi'                                     => 'KPI-1 ',
        'kpii'                                    => 'KPI-2 (card numérico)',
        'grafico_barra'                           => 'Gráfico de barras',
        'grafico_linha'                           => 'Gráfico de linha',
        'donut'                                   => 'Donut',
        'area'                                    => 'Área',
        'modelo_salvar'                           => 'Salvar modelo',
        'modelo_icon'                             => 'Ícone',
        'modelo_nome'                             => 'Nome do modelo',
        'modelo_nome_placeholder'                 => 'Ex.: Card de total de clientes',
        'modelo_descricao'                        => 'Descrição',
        'modelo_descricao_placeholder'            => 'Texto opcional sobre este gráfico/KPI.',
        'modelo_icone'                            => 'Ícone',
        'modelo_icone_hint'                       => 'Use classes Bootstrap Icons, por exemplo: bi bi-people-fill.',
        'modelo_info'                             => 'Tipo de destaque (info)',
        'modelo_tipo'                             => 'Tipo de gráfico / KPI',
        'modelo_exibicao'                         => 'Exibição',
        'modelo_ordem'                            => 'Ordem de exibição',
        'modelo_cor_principal'                    => 'Cor principal',
        'modelo_cor_secundaria'                   => 'Cor secundária',
        'modelo_atualizar'                        => 'Atualizar modelo',
        'modelo_nenhum'                           => 'Nenhum modelo cadastrado ainda.',
        'exibicao'                                => 'Exibição: ',
        'ordem'                                   => 'Ordem: ',
        'modelo_card'                             => 'Cartão',
        'modelo_full'                             => 'Completo',
        'modelo_grande'                           => 'Grande',
        'modelo_medio'                            => 'Médio',
        'modelo_pequeno'                          => 'Pequeno',
        'modelo_mini'                             => 'Mini',
        'modelo_micro'                            => 'Micro',         
        // API's
        'logout'                                  => 'Sair',
        'connection'                              => 'Conexão',
        'connection_success'                      => 'Conexão bem-sucedida',
        'connection_fail'                         => 'Falha na conexão: ',
        'db_exist'                                => '(sem banco selecionado)',
        'data'                                    => 'Data: ',
        'hora'                                    => 'Hora: ',

        'database'                                => 'Banco de dados',
        'db_name'                                 => 'Nome do banco: ',

        'server_info'                             => 'Informações do servidor',
        'php_version'                             => 'PHP: ',
        'server_version'                          => 'Servidor: ', 
        'host'                                    => 'Host: ',
        'smartoffice'                             => 'Smart Office 4.0',
        // ia.php 
        'relatorio'                               => 'Relatório I.A.',
        'parametros_ia'                           => 'Você é o "Smart IA", um assistente ANALÍTICO do sistema Smart Office 4.0. Responda SEMPRE em português do Brasil, de forma clara e direta.Você só pode responder sobre: dashboard, KPIs, gráficos, tendências, riscos e insights do negócio. Se o usuário perguntar algo fora disso, responda educadamente que só pode falar sobre análise do dashboard.',
        'erro_apikey'                             => 'Nenhuma API Key de IA configurada em dso_apikey_ia.',
        'erro_apikey_curl'                        => 'Erro ao chamar API (cURL): ',
        'erro_apikey_groq'                        => 'Erro da API Groq (HTTP ',
        'erro_apikey_groq_json'                   => 'Resposta JSON inválida da Groq.',
        'erro_apikey_groq_content'                => 'Resposta da Groq não contém conteúdo de mensagem.',
        'erro_apikey_groq_unknown'                => 'Erro desconhecido ao chamar a IA.',
        'parametros_iaa'                          => 'Gere um relatório completo, detalhado e técnico sobre os seguintes ',
        'parametros_iaaa'                         => 'gráficos e KPIs do Dashboard Smart Office 4.0, explicando o que está bom, ',
        'parametros_iaaaa'                        => 'o que preocupa e sugestões práticas de ações. Dados (JSON): ',
        'ia_graphic'                              => 'Qual gráfico você deseja analisar? Digite *exatamente* o nome exibido no Dashboard. Exemplo: `Gráfico: Donut - Clientes por status`',
        'ia_graphic_not_found'                    => '❌ Não encontrei esse gráfico. Digite o nome exatamente como aparece no Dashboard.',

        'ia_graphic_analyze'                      => 'Analise detalhadamente APENAS este gráfico do Dashboard Smart Office 4.0, ',
        'ia_graphic_analyzee'                     =>                'explicando o que ele mostra, tendências, riscos e oportunidades. ',
        'ia_graphic_data'                         =>                'Dados do gráfico (JSON): ',
        'ia_graphic_analyze_tendencies'           => 'Explique tendências e oportunidades com base nos seguintes gráficos e KPIs ',
        'ia_graphic_analyze_tendencies_2'         =>                'do Dashboard Smart Office 4.0. Foque em visão de negócio e possíveis ações. ',
        'ia_graphic_analyze_tendencies_data'      =>                'Dados (JSON): ',
        'ia_graphic_analyze_risks'                => 'Explique todos os riscos detectados nos gráficos e KPIs abaixo, ',
        'ia_graphic_analyze_risks_data'           =>                'indicando possíveis causas e recomendações. Dados (JSON): ',
        'ia_graphic_analyze_insights'             => 'Gere insights estratégicos e automáticos baseados nos seguintes ',
        'ia_graphic_analyze_insights_data'        => 'gráficos e KPIs do Dashboard Smart Office 4.0. ',
        'ia_graphic_analyze_insights_data_json'   => 'Dados (JSON): ',
        'ia_graphic_analyze_insights_error'       => 'Desculpe, posso responder apenas dúvidas sobre o Dashboard e seus gráficos.',
        'ia_chat_title'                           => 'Assistente Inteligente (IA)',
        'ia_chat_user'                            => 'Eu',
        'ia_chat_placeholder'                     => 'Digite sua mensagem...',
        'ia_chat_send'                            => 'Enviar',
        'config_api_ia_model'                     => 'Modelo de IA',
        'config_model_mantem_atual'               => '(Manter modelo atual)',
        'config_api_ia_model_help'                => 'Selecione o modelo de IA a ser utilizado nos relatórios e análises.',
        'chat_menu'                               => 'Olá! Como posso ajudar?  
        Digite o número da opção desejada:

        1️⃣ Relatório completo do Dashboard  
        2️⃣ Relatório de um gráfico específico  
        3️⃣ Explicar tendências e oportunidades  
        4️⃣ Explicar riscos detectados  
        5️⃣ Insights automáticos',
      ],
      'en_US' => [
        // login.php
        'faca_login'                              => 'Log in to start your session.',
        'usuario'                                 => 'Username',
        'senha'                                   => 'Password',
        'lembrar'                                 => 'Remember me',
        'entrar'                                  => 'Sign in',
        'esqueci_senha'                           => 'I forgot my password',
        
        // Toasts
        'falha_login'                             => 'Login failed',
        'usuario_nao_existe'                      => 'User does not exist.',
        'senha_invalida'                          => 'Invalid password.',
        'credenciais_invalidas'                   => 'Invalid credentials',
        'login_sucesso'                           => 'Login successful',
        'bem_vindo'                               => 'Welcome to Smart Office 4.0',
        'acessando_sistema'                       => 'Accessing system',
        'validando_credenciais'                   => 'Validating credentials...',
        'preencha_usuario_senha'                  => 'Fill in username and password.',
        'usuario_senha_incorretos'                => 'Incorrect username or password.',
        'redirecionando'                          => 'You will be redirected automatically...',
        'loading'                                 => 'Loading',

        // dashboard.php
        'dashboard'                               => 'Dashboard',

        // forgot-password.php
        'recuperar_senha'                         => 'Recover password',

        // preferences.php
        'preferencias'                            => 'Preferences',
        'config_server'                           => 'Server configuration',
        'config_home'                             => 'Home configuration',
        'config_exibir_home'                      => 'Show home page',
        'config_nao_exibir'                       => 'Do not show home page',
        'config_nao_exibir_help'                  => 'If selected, the home page will not be displayed.',
        'config_idioma'                           => 'Language settings',
        'config_idioma_help'                      => 'Select the system\'s preferred language.',
        'config_ptbr'                             => 'Portuguese (Brazil)',
        'config_enus'                             => 'English (United States)',
        'config_eses'                             => 'Spanish (Spain)',
        'config_salva'                            => 'Save preferences',

        'config_api_ia'                           => 'GROQ API Key Configuration',
        'config_cole_apikey'                      => 'Paste your key here (sk-...)',
        'config_api_ia_help'                      => 'Insert the AI API key provided by OpenAI.',
        'config_atual_mascarada'                  => 'Current key (masked):',
        'config_erro'                             => 'Error',
        'config_sucesso'                          => 'Success',
        'config_info'                             => 'Information',
        'config_salva_ok'                         => 'Preferences saved.',
        'config_api_salva_ok'                     => 'API Key updated successfully.',
        'config_api_vazia_ignorada'               => 'Empty key — nothing to update.',
        'config_csrf_invalido'                    => 'Session expired. Refresh the page and try again.',
        'config_seguranca_dica'                   => 'Tip: we do not display the full key; enter a new one to update.',
        'config_connection_success'               => 'Connection OK',
        'config_connection_fail'                  => 'Failure: ',
        'config_db_exist'                         => 'Database does not exist',

        // tabelas.php
        'list_database'                           => 'Table List',

        // novagrafico.php
        'configurar_metricas_graficos'            => 'Configure Metrics',
        'configuracoes_metricase_graficos'        => 'Configure Metrics &amp; Charts',
        'modelo_de_exibicao'                      => '3. Display models (dso_model_grafico)',
        'definir_join'                            => '2. Define JOINs',
        'definir_metrica'                         => '1. Define metric',
        'nome_da_metrica'                         => 'Metric name *',
        'tabela_principal'                        => 'Main table *',
        'tabela_schema'                           => 'Schema tables',
        'colunas_grupo'                           => 'Grouping columns (coluna_grupo)',
        'colunas_grupo_help'                      => 'Select one or more columns to group (by status, by branch, etc).',
        'colunas_valor'                           => 'Value column (coluna_valor)',
        'colunas_valor_help'                      => 'If nothing is selected, <code>COUNT(*)</code> will be used.',
        'filtro_where'                            => 'WHERE filter (optional)',
        'cancelar_edicao'                         => 'Cancel editing',
        'modelo_metrica'                          => 'Metric',
        'metricas_cadastradas'                    => 'Registered metrics',
        'editando_id'                             => 'Editing ID #',
        'tabela_juntar'                           => 'Table to join',
        'tabela_juntar_help'                      => 'Ex.: clients, contracts, gym, etc.',
        'alias'                                   => 'Alias',
        'tipo_join'                               => 'JOIN type',
        'condicao_on'                             => 'ON condition *',
        'condicao_on_help'                        => 'Use consistent aliases (ex.: ct, c, a).',
        'nenhum_join_cadastrado'                  => 'No JOIN registered yet.',
        'selecione'                               => '-- select --',
        'descricao'                               => 'Description',
        'agregacao'                               => 'Aggregation',
        'count'                                   => 'COUNT',
        'sum'                                     => 'SUM',
        'avg'                                     => 'AVERAGE',
        'min'                                     => 'MINIMUM',
        'max'                                     => 'MAXIMUM',
        'nenhuma_metrica_cadastrada'              => 'No metrics registered yet.',
        'nome'                                    => 'Name',
        'acoes'                                   => 'Actions',
        'tabela_alias'                            => 'Table (alias)',
        'condicao_onn'                            => 'ON',
        'box_azul'                                => 'Blue',
        'box_amarelo'                             => 'Yellow',
        'box_verde'                               => 'Green',
        'box_vermelho'                            => 'Red',
        'kpi'                                     => 'KPI-1',
        'kpii'                                    => 'KPI-2 (numeric card)',
        'grafico_barra'                           => 'Bar chart',
        'grafico_linha'                           => 'Line chart',
        'donut'                                   => 'Donut',
        'area'                                    => 'Area',
        'modelo_salvar'                           => 'Save model',
        'modelo_icon'                             => 'Icon',
        'modelo_nome'                             => 'Model name',
        'modelo_nome_placeholder'                 => 'Ex.: Total customers card',
        'modelo_descricao'                        => 'Description',
        'modelo_descricao_placeholder'            => 'Optional text about this chart/KPI.',
        'modelo_icone'                            => 'Icon',
        'modelo_icone_hint'                       => 'Use Bootstrap Icons classes, ex.: bi bi-people-fill.',
        'modelo_info'                             => 'Highlight type (info)',
        'modelo_tipo'                             => 'Chart / KPI type',
        'modelo_exibicao'                         => 'Display',
        'modelo_ordem'                            => 'Display order',
        'modelo_cor_principal'                    => 'Main color',
        'modelo_cor_secundaria'                   => 'Secondary color',
        'modelo_atualizar'                        => 'Update model',
        'modelo_nenhum'                           => 'No model registered yet.',
        'exibicao'                                => 'Display: ',
        'ordem'                                   => 'Order: ',
        'modelo_card'                             => 'Card',
        'modelo_full'                             => 'Full',
        'modelo_grande'                           => 'Large',
        'modelo_medio'                            => 'Medium',
        'modelo_pequeno'                          => 'Small',
        'modelo_mini'                             => 'Mini',
        'modelo_micro'                            => 'Micro',

        // API's
        'logout'                                  => 'Logout',
        'connection'                              => 'Connection',
        'connection_success'                      => 'Successful connection',
        'connection_fail'                         => 'Connection failed: ',
        'db_exist'                                => '(no database selected)',
        'data'                                    => 'Date: ',
        'hora'                                    => 'Time: ',
        
        'database'                                => 'Database',
        'db_name'                                 => 'Database name: ',

        'server_info'                             => 'Server information',
        'php_version'                             => 'PHP: ',
        'server_version'                          => 'Server: ',
        'host'                                    => 'Host: ',
        'smartoffice'                             => 'Smart Office 4.0',

        // ia.php
        'relatorio'                               => 'AI Report',
        'parametros_ia'                           => 'You are "Smart IA", an ANALYTICAL assistant of the Smart Office 4.0 system. Always answer in Brazilian Portuguese, clearly and directly. You can only answer about: dashboard, KPIs, charts, trends, risks and business insights. If the user asks something outside these topics, politely inform that you can only talk about dashboard analysis.',
        'erro_apikey'                             => 'No AI API Key configured in dso_apikey_ia.',
        'erro_apikey_curl'                        => 'API call error (cURL): ',
        'erro_apikey_groq'                        => 'Groq API error (HTTP ',
        'erro_apikey_groq_json'                   => 'Invalid JSON from Groq.',
        'erro_apikey_groq_content'                => 'Groq response does not contain message content.',
        'erro_apikey_groq_unknown'                => 'Unknown error calling AI.',
        'parametros_iaa'                          => 'Generate a complete, detailed and technical report about the following ',
        'parametros_iaaa'                         => 'charts and KPIs from the Smart Office 4.0 Dashboard, explaining what is good, ',
        'parametros_iaaaa'                        => 'what is concerning and practical action suggestions. Data (JSON): ',
        'ia_graphic'                              => 'Which chart do you want to analyze? Type *exactly* the name shown in the Dashboard. Example: `Chart: Donut - Customers by Status`',
        'ia_graphic_not_found'                    => '❌ Could not find this chart. Type the name exactly as it appears in the Dashboard.',

        'ia_graphic_analyze'                      => 'Analyze in detail ONLY this chart from the Smart Office 4.0 Dashboard, ',
        'ia_graphic_analyzee'                     => 'explaining what it shows, trends, risks and opportunities. ',
        'ia_graphic_data'                         => 'Chart data (JSON): ',
        'ia_graphic_analyze_tendencies'           => 'Explain trends and opportunities based on the following charts and KPIs ',
        'ia_graphic_analyze_tendencies_2'         => 'from the Smart Office 4.0 Dashboard. Focus on business vision and possible actions. ',
        'ia_graphic_analyze_tendencies_data'      => 'Data (JSON): ',
        'ia_graphic_analyze_risks'                => 'Explain all risks detected in the charts and KPIs below, ',
        'ia_graphic_analyze_risks_data'           => 'indicating possible causes and recommendations. Data (JSON): ',
        'ia_graphic_analyze_insights'             => 'Generate strategic and automatic insights based on the following ',
        'ia_graphic_analyze_insights_data'        => 'charts and KPIs from the Smart Office 4.0 Dashboard. ',
        'ia_graphic_analyze_insights_data_json'   => 'Data (JSON): ',
        'ia_graphic_analyze_insights_error'       => 'Sorry, I can only answer questions about the Dashboard and its charts.',
        'ia_chat_title'                           => 'Intelligent Assistant (AI)',
        'ia_chat_user'                            => 'Me',
        'ia_chat_placeholder'                     => 'Type your message...',
        'ia_chat_send'                            => 'Send',
        'config_api_ia_model'                     => 'AI Model',
        'config_model_mantem_atual'               => '(Keep current model)',
        'config_api_ia_model_help'                => 'Select the AI model to generate reports and analyses.',
        'chat_menu'                               => "Hello! How can I help?  
        Type the number of the desired option:

        1️⃣ Full Dashboard report  
        2️⃣ Report of a specific chart  
        3️⃣ Explain trends and opportunities  
        4️⃣ Explain detected risks  
        5️⃣ Automatic insights",
      ],
      'es_ES' => [
        // login.php
        'faca_login'                              => 'Inicia sesión para comenzar tu sesión.',
        'usuario'                                 => 'Usuario',
        'senha'                                   => 'Contraseña',
        'lembrar'                                 => 'Recordarme',
        'entrar'                                  => 'Entrar',
        'esqueci_senha'                           => 'Olvidé mi contraseña',

        // Toasts
        'falha_login'                             => 'Error de inicio de sesión',
        'usuario_nao_existe'                      => 'El usuario no existe.',
        'senha_invalida'                          => 'Contraseña inválida.',
        'credenciais_invalidas'                   => 'Credenciales inválidas',
        'login_sucesso'                           => 'Inicio de sesión exitoso',
        'bem_vindo'                               => 'Bienvenido a Smart Office 4.0',
        'acessando_sistema'                       => 'Accediendo al sistema',
        'validando_credenciais'                   => 'Validando credenciales...',
        'preencha_usuario_senha'                  => 'Rellena usuario y contraseña.',
        'usuario_senha_incorretos'                => 'Usuario o contraseña incorrectos.',
        'redirecionando'                          => 'Serás redirigido automáticamente...',
        'loading'                                 => 'Cargando',

        // dashboard.php
        'dashboard'                               => 'Panel',

        // forgot-password.php
        'recuperar_senha'                         => 'Recuperar contraseña',

        // preferences.php
        'preferencias'                            => 'Preferencias',
        'config_server'                           => 'Configuración del servidor',
        'config_home'                             => 'Configuración de la página inicial',
        'config_exibir_home'                      => 'Mostrar página de inicio',
        'config_nao_exibir'                       => 'No mostrar página de inicio',
        'config_nao_exibir_help'                  => 'Si seleccionas esta opción, no se mostrará la página de inicio.',
        'config_idioma'                           => 'Configuración de idioma',
        'config_idioma_help'                      => 'Selecciona el idioma preferido del sistema.',
        'config_ptbr'                             => 'Portugués (Brasil)',
        'config_enus'                             => 'Inglés (Estados Unidos)',
        'config_eses'                             => 'Español (España)',
        'config_salva'                            => 'Guardar preferencias',

        'config_api_ia'                           => 'Configuración de la API Key de GROQ',
        'config_cole_apikey'                      => 'Pega tu clave aquí (sk-...)',
        'config_api_ia_help'                      => 'Introduce la clave API proporcionada por OpenAI.',
        'config_atual_mascarada'                  => 'Clave actual (enmascarada):',
        'config_erro'                             => 'Error',
        'config_sucesso'                          => 'Éxito',
        'config_info'                             => 'Información',
        'config_salva_ok'                         => 'Preferencias guardadas.',
        'config_api_salva_ok'                     => 'API Key actualizada con éxito.',
        'config_api_vazia_ignorada'               => 'Clave vacía — nada que actualizar.',
        'config_csrf_invalido'                    => 'Sesión expirada. Actualiza la página e inténtalo de nuevo.',
        'config_seguranca_dica'                   => 'Consejo: no mostramos la clave completa; ingresa una nueva para actualizar.',
        'config_connection_success'               => 'Conexión OK',
        'config_connection_fail'                  => 'Fallo: ',
        'config_db_exist'                         => 'Base de datos inexistente',

        // tabelas.php
        'list_database'                           => 'Lista de tablas',

        // novagrafico.php
        'configurar_metricas_graficos'            => 'Configurar métricas',
        'configuracoes_metricase_graficos'        => 'Configurar métricas &amp; gráficos',
        'modelo_de_exibicao'                      => '3. Modelos de visualización (dso_model_grafico)',
        'definir_join'                            => '2. Definir JOINs',
        'definir_metrica'                         => '1. Definir métrica',
        'nome_da_metrica'                         => 'Nombre de la métrica *',
        'tabela_principal'                        => 'Tabla principal *',
        'tabela_schema'                           => 'Tablas del esquema',
        'colunas_grupo'                           => 'Columnas de agrupación (coluna_grupo)',
        'colunas_grupo_help'                      => 'Selecciona una o más columnas para agrupar (por estado, por sucursal, etc).',
        'colunas_valor'                           => 'Columna de valor (coluna_valor)',
        'colunas_valor_help'                      => 'Si no seleccionas nada, se usará <code>COUNT(*)</code>.',
        'filtro_where'                            => 'Filtro WHERE (opcional)',
        'cancelar_edicao'                         => 'Cancelar edición',
        'modelo_metrica'                          => 'Métrica',
        'metricas_cadastradas'                    => 'Métricas registradas',
        'editando_id'                             => 'Editando ID #',
        'tabela_juntar'                           => 'Tabla para unir',
        'tabela_juntar_help'                      => 'Ej.: clientes, contratos, academia, etc.',
        'alias'                                   => 'Alias',
        'tipo_join'                               => 'Tipo de JOIN',
        'condicao_on'                             => 'Condición ON *',
        'condicao_on_help'                        => 'Usa alias coherentes (ej.: ct, c, a).',
        'nenhum_join_cadastrado'                  => 'Ningún JOIN registrado aún.',
        'selecione'                               => '-- seleccionar --',
        'descricao'                               => 'Descripción',
        'agregacao'                               => 'Agregación',
        'count'                                   => 'CONTEO',
        'sum'                                     => 'SUMA',
        'avg'                                     => 'PROMEDIO',
        'min'                                     => 'MÍNIMO',
        'max'                                     => 'MÁXIMO',
        'nenhuma_metrica_cadastrada'              => 'Ninguna métrica registrada.',
        'nome'                                    => 'Nombre',
        'acoes'                                   => 'Acciones',
        'tabela_alias'                            => 'Tabla (alias)',
        'condicao_onn'                            => 'ON',
        'box_azul'                                => 'Azul',
        'box_amarelo'                             => 'Amarillo',
        'box_verde'                               => 'Verde',
        'box_vermelho'                            => 'Rojo',
        'kpi'                                     => 'KPI-1',
        'kpii'                                    => 'KPI-2 (tarjeta numérica)',
        'grafico_barra'                           => 'Gráfico de barras',
        'grafico_linha'                           => 'Gráfico de líneas',
        'donut'                                   => 'Donut',
        'area'                                    => 'Área',
        'modelo_salvar'                           => 'Guardar modelo',
        'modelo_icon'                             => 'Ícono',
        'modelo_nome'                             => 'Nombre del modelo',
        'modelo_nome_placeholder'                 => 'Ej.: Tarjeta total de clientes',
        'modelo_descricao'                        => 'Descripción',
        'modelo_descricao_placeholder'            => 'Texto opcional sobre este gráfico/KPI.',
        'modelo_icone'                            => 'Ícono',
        'modelo_icone_hint'                       => 'Usa clases de Bootstrap Icons, ej.: bi bi-people-fill.',
        'modelo_info'                             => 'Tipo de destaque (info)',
        'modelo_tipo'                             => 'Tipo de gráfico / KPI',
        'modelo_exibicao'                         => 'Visualización',
        'modelo_ordem'                            => 'Orden de visualización',
        'modelo_cor_principal'                    => 'Color principal',
        'modelo_cor_secundaria'                   => 'Color secundario',
        'modelo_atualizar'                        => 'Actualizar modelo',
        'modelo_nenhum'                           => 'Ningún modelo registrado.',
        'exibicao'                                => 'Visualización: ',
        'ordem'                                   => 'Orden: ',
        'modelo_card'                             => 'Tarjeta',
        'modelo_full'                             => 'Completo',
        'modelo_grande'                           => 'Grande',
        'modelo_medio'                            => 'Mediano',
        'modelo_pequeno'                          => 'Pequeño',
        'modelo_mini'                             => 'Mini',
        'modelo_micro'                            => 'Micro',

        // API´s
        'logout'                                  => 'Salir',
        'connection'                              => 'Conexión',
        'connection_success'                      => 'Conexión exitosa',
        'connection_fail'                         => 'Fallo en la conexión: ',
        'db_exist'                                => '(sin base de datos seleccionada)',
        'data'                                    => 'Fecha: ',
        'hora'                                    => 'Hora: ',
        
        'database'                                => 'Base de datos',
        'db_name'                                 => 'Nombre de la base: ',

        'server_info'                             => 'Información del servidor',
        'php_version'                             => 'PHP: ',
        'server_version'                          => 'Servidor: ',
        'host'                                    => 'Host: ',
        'smartoffice'                             => 'Smart Office 4.0',

        // ia.php
        'relatorio'                               => 'Informe de IA',
        'parametros_ia'                           => 'Eres "Smart IA", un asistente ANALÍTICO del sistema Smart Office 4.0. Responde SIEMPRE en portugués brasileño, de manera clara y directa. Solo puedes responder sobre: panel, KPIs, gráficos, tendencias, riesgos e insights del negocio. Si el usuario pregunta algo fuera de esto, responde educadamente que solo puedes hablar del análisis del panel.',
        'erro_apikey'                             => 'Ninguna API Key de IA configurada en dso_apikey_ia.',
        'erro_apikey_curl'                        => 'Error al llamar a la API (cURL): ',
        'erro_apikey_groq'                        => 'Error de la API Groq (HTTP ',
        'erro_apikey_groq_json'                   => 'JSON inválido recibido de Groq.',
        'erro_apikey_groq_content'                => 'La respuesta de Groq no contiene contenido de mensaje.',
        'erro_apikey_groq_unknown'                => 'Error desconocido al llamar a la IA.',
        'parametros_iaa'                          => 'Genera un informe completo, detallado y técnico sobre los siguientes ',
        'parametros_iaaa'                         => 'gráficos y KPIs del Panel Smart Office 4.0, explicando lo que está bien, ',
        'parametros_iaaaa'                        => 'lo que preocupa y sugerencias prácticas de acciones. Datos (JSON): ',
        'ia_graphic'                              => '¿Qué gráfico deseas analizar? Escribe *exactamente* el nombre mostrado en el Panel. Ej.: `Gráfico: Donut - Clientes por estado`',
        'ia_graphic_not_found'                    => '❌ No encontré ese gráfico. Escribe el nombre exactamente como aparece en el Panel.',

        'ia_graphic_analyze'                      => 'Analiza detalladamente SOLO este gráfico del Panel Smart Office 4.0, ',
        'ia_graphic_analyzee'                     => 'explicando lo que muestra, tendencias, riesgos y oportunidades. ',
        'ia_graphic_data'                         => 'Datos del gráfico (JSON): ',
        'ia_graphic_analyze_tendencies'           => 'Explica tendencias y oportunidades basadas en los siguientes gráficos y KPIs ',
        'ia_graphic_analyze_tendencies_2'         => 'del Panel Smart Office 4.0. Enfócate en visión de negocio y acciones posibles. ',
        'ia_graphic_analyze_tendencies_data'      => 'Datos (JSON): ',
        'ia_graphic_analyze_risks'                => 'Explica todos los riesgos detectados en los gráficos y KPIs abajo, ',
        'ia_graphic_analyze_risks_data'           => 'indicando posibles causas y recomendaciones. Datos (JSON): ',
        'ia_graphic_analyze_insights'             => 'Genera insights estratégicos y automáticos basados en los siguientes ',
        'ia_graphic_analyze_insights_data'        => 'gráficos y KPIs del Panel Smart Office 4.0. ',
        'ia_graphic_analyze_insights_data_json'   => 'Datos (JSON): ',
        'ia_graphic_analyze_insights_error'       => 'Lo siento, solo puedo responder dudas sobre el Panel y sus gráficos.',
        'ia_chat_title'                           => 'Asistente Inteligente (IA)',
        'ia_chat_user'                            => 'Yo',
        'ia_chat_placeholder'                     => 'Escribe tu mensaje...',
        'ia_chat_send'                            => 'Enviar',
        'config_api_ia_model'                     => 'Modelo de IA',
        'config_model_mantem_atual'               => '(Mantener modelo actual)',
        'config_api_ia_model_help'                => 'Selecciona el modelo de IA para los informes y análisis.',
        'chat_menu'                               => "¡Hola! ¿Cómo puedo ayudarte?  
        Escribe el número de la opción deseada:

        1️⃣ Informe completo del Panel  
        2️⃣ Informe de un gráfico específico  
        3️⃣ Explicar tendencias y oportunidades  
        4️⃣ Explicar riesgos detectados  
        5️⃣ Insights automáticos",
      ],
    ];
    $this->strings = isset($languages[$lang]) ? $languages[$lang] : $languages['pt_BR'];
  }

  public function get($key) { return isset($this->strings[$key]) ? $this->strings[$key] : "[$key]"; }
  public function __get($key) { return $this->get($key); }
  public function __invoke($key) { return $this->get($key); }
  public function all() { return $this->strings; }
}

